### ISSUE TITLE
麻烦检查优化下你的邮箱的自动回复规则

### ISSUE THREAD

**Issue by mzlogin** [xueche/xueche.github.io#1]
目前你的邮箱可能有自动回复，会导致你参与过的 GitHub Issue / Discussion 有新的动态时，会自动回复跟贴，比如：

https://github.com/mzlogin/blog-comments/discussions/204#discussioncomment-6600272

这可能产生一些垃圾回复不利于讨论问题，麻烦检查下～多谢。

**Comment by xueche** [comment]
抱歉，已关闭邮件自动回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xueche/xueche.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月1日(星期二) 上午9:46
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xueche/xueche.github.io] 麻烦检查优化下你的邮箱的自动回复规则 (Issue #1)





 
目前你的邮箱可能有自动回复，会导致你参与过的 GitHub Issue / Discussion 有新的动态时，会自动回复跟贴，比如：
 
mzlogin/blog-comments#204 (comment)
 
这可能产生一些垃圾回复不利于讨论问题，麻烦检查下～多谢。
